# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QT_VERSION: 5.14.2


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: "macOS Latest x64"
    runs-on: macos-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '${{ env.QT_VERSION }}'
        host: 'mac'
        target: 'desktop'
        dir: '${{ github.workspace }}'
        install-deps: 'true'
        modules: 'qtcharts qtdatavis3d qtwebengine'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: 'false'

    - name: fetch submodule
      run: git submodule update --init
    - name: build swag
      run: |
          qmake -spec macx-clang "CONFIG+=release"
          make
    - name: create dmg
      run: |
          chmod a+x ./deploy2mac.sh
          set( qtroot "${{ github.workspace }}/qt/${{ env.QT_VERSION }}/")
          QT_PATH = $ENV{QTDIR}
          QT_PATH = ${QT_PATH:0:${#QT_PATH} - 3}
          ./deploy2mac.sh ${{ github.workspace }}
    - name: Upload dmg
      uses: actions/upload-artifact@v1
      with:
        name: swag-macos-${{ env.QT_VERSION }}.dmg
        path: ./deploy/macos/swag.dmg
